version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      target: dev
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    depends_on:
      - backend
    
  backend:
    container_name: backend
    build:
      context: ./backend
      target: dev
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=dev
    ports: 
      - 5000:5000
